# CMake generated Testfile for 
# Source directory: /Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit
# Build directory: /Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("test_bmp280_model" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_bmp280_model")
set_tests_properties("test_bmp280_model" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_coverage_gate" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_coverage_gate")
set_tests_properties("test_coverage_gate" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_hal_display_sim" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_hal_display_sim")
set_tests_properties("test_hal_display_sim" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_hal_gpio_sim" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_hal_gpio_sim")
set_tests_properties("test_hal_gpio_sim" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_hal_i2c_sim" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_hal_i2c_sim")
set_tests_properties("test_hal_i2c_sim" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_headless_exit" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_headless_exit")
set_tests_properties("test_headless_exit" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_junit_output" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_junit_output")
set_tests_properties("test_junit_output" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_kernel_alloc" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_kernel_alloc")
set_tests_properties("test_kernel_alloc" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_kernel_boot" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_kernel_boot")
set_tests_properties("test_kernel_boot" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_kernel_time" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_kernel_time")
set_tests_properties("test_kernel_time" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_sim_args" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_sim_args")
set_tests_properties("test_sim_args" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_sim_audio" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_sim_audio")
set_tests_properties("test_sim_audio" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_sim_device_reg" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_sim_device_reg")
set_tests_properties("test_sim_device_reg" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_sim_gpio_keys" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_sim_gpio_keys")
set_tests_properties("test_sim_gpio_keys" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_sim_storage" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_sim_storage")
set_tests_properties("test_sim_storage" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_ssd1306_model" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_ssd1306_model")
set_tests_properties("test_ssd1306_model" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
add_test("test_tdd_hook" "/Users/arashrasoulzadeh/Documents/projects/ardubot/build5/tests/unit/test_tdd_hook")
set_tests_properties("test_tdd_hook" PROPERTIES  _BACKTRACE_TRIPLES "/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;38;add_test;/Users/arashrasoulzadeh/Documents/projects/ardubot/tests/unit/CMakeLists.txt;0;")
